# Generated by Django 4.2.4 on 2023-08-21 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_table_alter_groupcompany_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
        ('general_config', '0003_remove_religion_user_remove_title_user'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.CharField(blank=True, max_length=150, null=True)),
                ('signature', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True)),
                ('pr_address', models.CharField(max_length=240, verbose_name='Present Address')),
                ('pr_district', models.CharField(max_length=25)),
                ('pr_police_station', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_post_code', models.CharField(max_length=4)),
                ('pm_address', models.CharField(blank=True, max_length=240, null=True, verbose_name='Permanent Address')),
                ('pm_district', models.CharField(max_length=25)),
                ('pm_police_station', models.CharField(blank=True, max_length=50, null=True)),
                ('pm_post_code', models.CharField(max_length=4)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('biography', models.CharField(blank=True, max_length=150, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(blank=True, max_length=30, null=True)),
                ('last_education', models.CharField(blank=True, max_length=240, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general_config.religion')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general_config.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emp_personals',
            },
        ),
        migrations.CreateModel(
            name='EmpProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(unique=True)),
                ('pf_no', models.PositiveIntegerField(default=0)),
                ('report_to', models.PositiveIntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('card_no', models.CharField(blank=True, max_length=30, null=True)),
                ('card_printed', models.BooleanField(default=False)),
                ('overtime', models.BooleanField(default=False, verbose_name='Overtime Eligibility')),
                ('overtime_note', models.TextField(blank=True, default='', null=True, verbose_name='Overtime Instructions')),
                ('transport', models.BooleanField(default=False, verbose_name='Transport Eligibility')),
                ('transport_note', models.TextField(blank=True, null=True, verbose_name='Transport Instructions')),
                ('pay_schale', models.PositiveIntegerField(default=0)),
                ('pay_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('confirm_probation', models.CharField(default='P', max_length=1)),
                ('confirm_period', models.PositiveIntegerField(default=0)),
                ('bank_acc_no', models.CharField(blank=True, max_length=17, null=True)),
                ('status_change_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general_config.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='department.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='designation.designation')),
                ('emp_personals_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.emppersonal')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='department.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('working_status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general_config.working_status')),
            ],
            options={
                'db_table': 'emp_professionals',
            },
        ),
    ]
