# Generated by Django 4.2.4 on 2023-08-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empprofessional',
            old_name='emp_personals_id',
            new_name='emp_personals',
        ),
    ]
