# Generated by Django 4.2.4 on 2023-09-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_emp_personals_empprofessional_emp_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employee/'),
        ),
        migrations.AlterField(
            model_name='emppersonal',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signature/'),
        ),
    ]
