# Generated by Django 4.2.4 on 2023-09-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0003_remove_religion_user_remove_title_user'),
        ('employee', '0006_alter_emppersonal_pm_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofessional',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='general_config.bank'),
        ),
    ]
