# Generated by Django 4.2.4 on 2023-08-19 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banks',
            new_name='Bank',
        ),
        migrations.RenameModel(
            old_name='Religions',
            new_name='Religion',
        ),
    ]
