# Generated by Django 4.2.4 on 2023-08-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0002_rename_banks_bank_rename_religions_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
    ]
