# Generated by Django 4.1.9 on 2023-07-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_ledger',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.supplier', unique=True),
        ),
    ]
