# Generated by Django 4.1.9 on 2023-07-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplierpayment_supplieraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_ledger',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.supplier'),
        ),
    ]
