# Generated by Django 4.1.9 on 2023-07-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_ledger_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='check_no',
        ),
    ]
