# Generated by Django 4.2.4 on 2023-08-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True, unique=True)),
                ('website', models.URLField(blank=True, max_length=190, null=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('locale', models.CharField(default='en-US', help_text='English, Bangla', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'group_companies',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=190, null=True)),
                ('logo_img', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.groupcompany')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
