# Generated by Django 4.2.4 on 2023-08-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='groupcompany',
            table=None,
        ),
    ]
