# Generated by Django 4.2.4 on 2023-08-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_table_alter_groupcompany_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='groupcompany',
            table='group_company',
        ),
    ]
