# Generated by Django 4.1.9 on 2023-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='strat_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
    ]
