# Generated by Django 4.1.9 on 2023-07-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_rename_strat_date_site_start_date_alter_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='district',
            field=models.CharField(default='Dhaka', max_length=240),
        ),
        migrations.AlterField(
            model_name='site',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
