# Generated by Django 4.1.9 on 2023-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
