# Generated by Django 4.2.4 on 2023-08-19 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_alter_company_table_alter_groupcompany_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('started_from', models.DateField(default=datetime.date.today)),
                ('report_to', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_authority', models.PositiveIntegerField(blank=True, null=True)),
                ('headed_by', models.PositiveIntegerField(blank=True, null=True)),
                ('second_man', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('emp_count', models.PositiveIntegerField(default=0)),
                ('approved_manpower', models.PositiveIntegerField(default=0)),
                ('top_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('roster_year', models.PositiveIntegerField(default=2023)),
                ('roster_month_id', models.PositiveIntegerField(default=0)),
                ('leave_steps', models.CharField(default='1111', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('started_from', models.DateField(auto_now_add=True)),
                ('report_to', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_authority', models.PositiveIntegerField(blank=True, null=True)),
                ('headed_by', models.PositiveIntegerField(blank=True, null=True)),
                ('second_man', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('emp_count', models.PositiveIntegerField(default=0)),
                ('approved_manpower', models.PositiveIntegerField(default=0)),
                ('top_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='department.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
    ]
