# Generated by Django 4.1.9 on 2023-07-12 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0003_alter_supplier_ledger_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('construction', '0004_alter_site_district_alter_site_end_date_and_more'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invice_no', models.CharField(max_length=20, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='construction.site')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchase.purchase')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='construction.site')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
