# Generated by Django 4.1.9 on 2023-07-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='invice_no',
            new_name='invoice_no',
        ),
    ]
